// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUser struct {
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
}

type Query struct {
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
}
